### ISSUE TITLE
tf-gitea to support threefold connect

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tf-gitea#12]
## phase 1

- [x] prepare a fork
- [x] prepare the build pipeline (build pipelines don't work on forks on github)
- [x] prepare the helm charts
- [x] make sure VDC marketplace works against the forked solutions
- [x] integrate threefold connect (should be a button to loging with threefold connect that starts the auth flow) + callback endpoint that creates the users -how do we deal with different roles?- if these solutions are exposed on the public internet?

NOTE: there's no need to use oauth-proxy not the deployed one or the sidecar, because the flow is implemented in gitea directly 
note: this issue doesn't address anything related to mobile/desktop apps for the solutions, it'd be only usable from the web browser

**Comment by waleedhammam** [comment]
Deployed vdc: monday 22feb

![Screenshot from 2021-02-23 16-21-08](https://user-images.githubusercontent.com/10658229/108856890-3284d180-75f3-11eb-9248-c2068defcd94.png)
![Screenshot from 2021-02-23 16-20-44](https://user-images.githubusercontent.com/10658229/108856894-331d6800-75f3-11eb-9c4b-f8b6c814c648.png)
![Screenshot from 2021-02-23 16-20-36](https://user-images.githubusercontent.com/10658229/108856902-34e72b80-75f3-11eb-8f66-2f3d61bc0f18.png)


Verified
